"""
explain.py — SHAP-based explainability module for PhishGuard.

WHY SHAP OVER feature_importances_:
    feature_importances_ gives GLOBAL importance across all training samples.
    SHAP gives LOCAL importance — which features mattered for THIS specific
    prediction. A security analyst asking "why was this URL flagged?" needs
    the local explanation.

FALLBACK:
    If SHAP fails, falls back to a threshold-based heuristic computing each
    feature's deviation from class-conditional means. Less statistically rigorous
    but still meaningful and reportable as a documented design tradeoff.
"""

import shap
import numpy as np
import pandas as pd
import joblib
from pathlib import Path
from typing import List, Dict, Any

MODELS_DIR = Path("models")
PROCESSED_DIR = Path("data/processed")

FEATURE_NAMES = [
    "url_length", "has_ip_address", "has_at_symbol", "num_hyphens_in_domain",
    "num_dots", "num_subdomains", "has_https", "has_suspicious_tld",
    "has_url_shortener", "digit_ratio", "has_double_slash_in_path",
    "special_char_count", "domain_length", "has_brand_keyword_mismatch",
    "path_length", "num_query_params", "has_redirect_in_query",
    "url_entropy", "has_port_in_url",
]

FEATURE_DESCRIPTIONS = {
    "url_length":               "Unusually long URL (extra subdomains/params to mimic legitimate paths)",
    "has_ip_address":           "Uses raw IP address instead of domain name (strong phishing signal)",
    "has_at_symbol":            "Contains '@' in URL (classic browser obfuscation: paypal.com@attacker.ru)",
    "num_hyphens_in_domain":    "Multiple hyphens in domain name (e.g., paypal-secure-login.com)",
    "num_dots":                 "High number of dots (deep subdomain nesting for impersonation)",
    "num_subdomains":           "Multiple subdomains detected (brand impersonation pattern)",
    "has_https":                "Missing HTTPS — connection is unencrypted",
    "has_suspicious_tld":       "Suspicious TLD (.tk, .ml, .ga etc.) — heavily abused by phishers",
    "has_url_shortener":        "URL shortener detected (hides true destination from user)",
    "digit_ratio":              "High digit proportion (suggests algorithmically generated URL)",
    "has_double_slash_in_path": "Double slash in URL path (used for redirect tricks)",
    "special_char_count":       "Excessive special characters (URL encoding obfuscation)",
    "domain_length":            "Unusual domain name length (very long = DGA-generated)",
    "has_brand_keyword_mismatch": "Brand name in URL but registered domain doesn't match (impersonation)",
    "path_length":              "Very long URL path (auto-generated by phishing kits)",
    "num_query_params":         "Excessive query parameters (obfuscation/tracking)",
    "has_redirect_in_query":    "URL contains another URL in query string (open redirect attempt)",
    "url_entropy":              "High URL entropy (random/algorithmically generated characters)",
    "has_port_in_url":          "Non-standard port specified (anomalous for user-facing web URLs)",
}


class PhishExplainer:
    """Wraps a trained model with SHAP TreeExplainer for per-prediction explanations."""

    def __init__(self, model=None, model_path: str = "models/best_model.joblib"):
        self.model = model if model is not None else joblib.load(model_path)

        try:
            self.explainer = shap.TreeExplainer(self.model)
            self._use_shap = True
            print("PhishExplainer: Using SHAP TreeExplainer.")
        except Exception as e:
            print(f"PhishExplainer: SHAP failed ({e}). Using threshold-heuristic fallback.")
            self._use_shap = False
            self._load_class_means()

    def _load_class_means(self):
        """Load class-conditional means for fallback explanation."""
        try:
            train_df = pd.read_csv(PROCESSED_DIR / "train.csv")
            self._class_means = {
                label: train_df[train_df["label"] == label][FEATURE_NAMES].mean()
                for label in [0, 1]
            }
        except Exception:
            self._class_means = None

    def explain(self, feature_vector: Dict[str, Any], top_n: int = 5) -> List[Dict]:
        """
        Compute per-feature risk contributions for a single prediction.

        Returns:
            List of top_n dicts: {feature, value, contribution, description, direction}
            Sorted by |contribution| descending.
        """
        X = np.array([[feature_vector.get(f, 0) for f in FEATURE_NAMES]])
        return self._explain_shap(X, feature_vector, top_n) if self._use_shap \
               else self._explain_fallback(X, feature_vector, top_n)

    def _explain_shap(self, X, feature_vector, top_n):
        shap_values = self.explainer.shap_values(X)
        values = shap_values[1][0] if isinstance(shap_values, list) else shap_values[0]

        pairs = sorted(zip(FEATURE_NAMES, values), key=lambda x: abs(x[1]), reverse=True)
        return [{
            "feature": name,
            "value": feature_vector.get(name, 0),
            "contribution": round(float(val), 4),
            "description": FEATURE_DESCRIPTIONS.get(name, name),
            "direction": "phishing" if val > 0 else "legitimate",
        } for name, val in pairs[:top_n]]

    def _explain_fallback(self, X, feature_vector, top_n):
        if self._class_means is None:
            return []
        phish_means = self._class_means[1]
        legit_means = self._class_means[0]
        results = []
        for feat_name in FEATURE_NAMES:
            val = feature_vector.get(feat_name, 0)
            range_val = abs(phish_means.get(feat_name, 0) - legit_means.get(feat_name, 0)) + 1e-9
            contribution = (val - legit_means.get(feat_name, 0)) / range_val
            results.append({
                "feature": feat_name,
                "value": val,
                "contribution": round(float(contribution), 4),
                "description": FEATURE_DESCRIPTIONS.get(feat_name, feat_name),
                "direction": "phishing" if contribution > 0 else "legitimate",
            })
        return sorted(results, key=lambda x: abs(x["contribution"]), reverse=True)[:top_n]

    def generate_explanation_text(self, top_features: List[Dict], prediction: str) -> str:
        """Generate a natural-language explanation string for the UI."""
        if prediction == "phishing":
            phishing_factors = [f for f in top_features if f["direction"] == "phishing"]
            if not phishing_factors:
                return "This URL was flagged as suspicious based on multiple structural anomalies."
            top_two = phishing_factors[:2]
            descs = " and ".join(f["description"].lower() for f in top_two)
            return (f"This URL was flagged as phishing primarily due to: {descs}. "
                    f"These patterns are strongly associated with malicious URLs in the training data.")
        return ("This URL appears legitimate. No significant phishing indicators were detected. "
                "The URL follows structural patterns consistent with legitimate websites.")


def predict_and_explain(url: str, model=None) -> Dict[str, Any]:
    """
    End-to-end pipeline: raw URL → full output schema.
    This is the function called by the Streamlit app.
    """
    import sys
    sys.path.insert(0, ".")
    from src.features import extract_features

    if model is None:
        model = joblib.load("models/best_model.joblib")

    explainer = PhishExplainer(model=model)
    feature_vector = extract_features(url)
    X = np.array([[feature_vector.get(f, 0) for f in FEATURE_NAMES]])

    prediction_int = int(model.predict(X)[0])
    probability = float(model.predict_proba(X)[0][1])
    prediction_str = "phishing" if prediction_int == 1 else "legitimate"

    risk_label = (
        "High Risk" if probability >= 0.75 else
        "Medium Risk" if probability >= 0.45 else
        "Low Risk"
    )

    top_features = explainer.explain(feature_vector, top_n=5)
    explanation_text = explainer.generate_explanation_text(top_features, prediction_str)

    return {
        "url": url,
        "prediction": prediction_str,
        "probability": round(probability, 4),
        "risk_label": risk_label,
        "top_contributing_features": top_features,
        "explanation_text": explanation_text,
        "feature_vector": feature_vector,
    }
